'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.586
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.586.
'
Namespace SensorsService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SensorsServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SensorsService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private RetornaListaDeSensoresOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EstadoSensorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private RetornaListaEstadosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ExemploShapsinSensors.My.MySettings.Default.ExemploShapsinSensors_SensorsService_SensorsService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event RetornaListaDeSensoresCompleted As RetornaListaDeSensoresCompletedEventHandler
        
        '''<remarks/>
        Public Event EstadoSensorCompleted As EstadoSensorCompletedEventHandler
        
        '''<remarks/>
        Public Event RetornaListaEstadosCompleted As RetornaListaEstadosCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaListaDeSensores", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetornaListaDeSensores() As String()
            Dim results() As Object = Me.Invoke("RetornaListaDeSensores", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub RetornaListaDeSensoresAsync()
            Me.RetornaListaDeSensoresAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RetornaListaDeSensoresAsync(ByVal userState As Object)
            If (Me.RetornaListaDeSensoresOperationCompleted Is Nothing) Then
                Me.RetornaListaDeSensoresOperationCompleted = AddressOf Me.OnRetornaListaDeSensoresOperationCompleted
            End If
            Me.InvokeAsync("RetornaListaDeSensores", New Object(-1) {}, Me.RetornaListaDeSensoresOperationCompleted, userState)
        End Sub
        
        Private Sub OnRetornaListaDeSensoresOperationCompleted(ByVal arg As Object)
            If (Not (Me.RetornaListaDeSensoresCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RetornaListaDeSensoresCompleted(Me, New RetornaListaDeSensoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EstadoSensor", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EstadoSensor(ByVal id As String) As Integer
            Dim results() As Object = Me.Invoke("EstadoSensor", New Object() {id})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EstadoSensorAsync(ByVal id As String)
            Me.EstadoSensorAsync(id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EstadoSensorAsync(ByVal id As String, ByVal userState As Object)
            If (Me.EstadoSensorOperationCompleted Is Nothing) Then
                Me.EstadoSensorOperationCompleted = AddressOf Me.OnEstadoSensorOperationCompleted
            End If
            Me.InvokeAsync("EstadoSensor", New Object() {id}, Me.EstadoSensorOperationCompleted, userState)
        End Sub
        
        Private Sub OnEstadoSensorOperationCompleted(ByVal arg As Object)
            If (Not (Me.EstadoSensorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EstadoSensorCompleted(Me, New EstadoSensorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornaListaEstados", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetornaListaEstados() As String()
            Dim results() As Object = Me.Invoke("RetornaListaEstados", New Object(-1) {})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub RetornaListaEstadosAsync()
            Me.RetornaListaEstadosAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub RetornaListaEstadosAsync(ByVal userState As Object)
            If (Me.RetornaListaEstadosOperationCompleted Is Nothing) Then
                Me.RetornaListaEstadosOperationCompleted = AddressOf Me.OnRetornaListaEstadosOperationCompleted
            End If
            Me.InvokeAsync("RetornaListaEstados", New Object(-1) {}, Me.RetornaListaEstadosOperationCompleted, userState)
        End Sub
        
        Private Sub OnRetornaListaEstadosOperationCompleted(ByVal arg As Object)
            If (Not (Me.RetornaListaEstadosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent RetornaListaEstadosCompleted(Me, New RetornaListaEstadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub RetornaListaDeSensoresCompletedEventHandler(ByVal sender As Object, ByVal e As RetornaListaDeSensoresCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RetornaListaDeSensoresCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub EstadoSensorCompletedEventHandler(ByVal sender As Object, ByVal e As EstadoSensorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EstadoSensorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub RetornaListaEstadosCompletedEventHandler(ByVal sender As Object, ByVal e As RetornaListaEstadosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class RetornaListaEstadosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
End Namespace
